import { router, useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { ActivityIndicator, Text, View } from 'react-native';
import { ApiError, apiRequest } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton, Choice, Field, Screen, ui } from '@/components';
import { AssistantConversation, AssistantMessage } from '@/types';

export default function AssistantScreen(){
  const{conversationId}=useLocalSearchParams<{conversationId?:string}>();
  const{token}=useAuth();const[conversations,setConversations]=useState<AssistantConversation[]>([]);const[selected,setSelected]=useState(conversationId??'');const[messages,setMessages]=useState<AssistantMessage[]>([]);const[question,setQuestion]=useState('');const[notify,setNotify]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const load=useCallback(async()=>{if(!token)return;try{const rows=await apiRequest<AssistantConversation[]>('/assistant/conversations',{},token);setConversations(rows);let id=selected&&rows.some(x=>x.id===selected)?selected:rows[0]?.id;if(!id){const created=await apiRequest<AssistantConversation>('/assistant/conversations',{method:'POST',body:JSON.stringify({title:'Research conversation'})},token);id=created.id;setConversations([created]);}setSelected(id);const detail=await apiRequest<AssistantConversation>(`/assistant/conversations/${id}`,{},token);setMessages(detail.messages);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load assistant history.');}},[selected,token]);useFocusEffect(useCallback(()=>{void load();},[load]));
  async function choose(id:string){if(!token)return;setSelected(id);try{const detail=await apiRequest<AssistantConversation>(`/assistant/conversations/${id}`,{},token);setMessages(detail.messages);}catch(e){setError(e instanceof ApiError?e.message:'Could not load conversation.');}}
  async function create(){if(!token)return;try{const c=await apiRequest<AssistantConversation>('/assistant/conversations',{method:'POST',body:JSON.stringify({title:'Research conversation'})},token);setConversations(x=>[c,...x]);setSelected(c.id);setMessages([]);}catch(e){setError(e instanceof ApiError?e.message:'Could not create conversation.');}}
  async function send(){if(!token||!selected||!question.trim())return;setBusy(true);setError('');try{await apiRequest(`/assistant/conversations/${selected}/messages`,{method:'POST',body:JSON.stringify({message:question,notify_when_ready:notify})},token);setQuestion('');const detail=await apiRequest<AssistantConversation>(`/assistant/conversations/${selected}`,{},token);setMessages(detail.messages);}catch(e){setError(e instanceof ApiError?e.message:'Assistant request failed.');}finally{setBusy(false);}}
  async function remove(){if(!token||!selected)return;try{await apiRequest(`/assistant/conversations/${selected}`,{method:'DELETE'},token);setSelected('');setMessages([]);await load();}catch(e){setError(e instanceof ApiError?e.message:'Could not delete conversation.');}}
  return <Screen><Text style={ui.title}>Cited research assistant</Text><Text style={ui.subtitle}>Read-only explanations from your stored evidence. It cannot trade, edit records, or determine suitability, law, or tax.</Text>{error?<Text style={ui.error}>{error}</Text>:null}<ActionButton title="Feedback history and review" onPress={()=>router.push('/assistant-feedback' as never)}/><View style={ui.row}>{conversations.map(c=><Choice key={c.id} label={c.title} selected={selected===c.id} onPress={()=>void choose(c.id)}/>)}</View><ActionButton title="New conversation" onPress={()=>void create()}/>{messages.length===0?<Text style={ui.muted}>Ask about your ledger, holdings, past decisions, books, property evidence, or marketplace research.</Text>:messages.map(m=><View style={ui.card} key={m.id}><Text style={ui.cardTitle}>{m.role==='user'?'You':`Assistant Ã‚Â· ${m.response?.mode??'stored'}`}</Text><Text>{m.content}</Text>{m.response?.freshness.map(x=><Text style={ui.muted} key={x}>Freshness: {x}</Text>)}{m.response?<ActionButton title="Review evidence, limitations, or report response" onPress={()=>router.push({pathname:'/assistant-evidence',params:{conversationId:selected,messageId:m.id}} as never)}/>:null}</View>)}<Field label="Question" value={question} onChangeText={setQuestion} multiline maxLength={4000} placeholder="What evidence supports my last decision?"/><Choice label="Notify me on active devices when this answer is ready (off by default)" selected={notify} onPress={()=>setNotify(x=>!x)}/><ActionButton title="Search evidence and answer" onPress={()=>void send()} disabled={busy||!question.trim()}/>{busy?<ActivityIndicator/>:null}<ActionButton title="Delete this conversation" onPress={()=>void remove()} disabled={!selected}/></Screen>;
}
