import { router,useFocusEffect,useLocalSearchParams } from 'expo-router';
import { useCallback,useState } from 'react';
import { ActivityIndicator,Text,View } from 'react-native';
import { ApiError,apiRequest } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton,Choice,Field,Screen,ui } from '@/components';
import { AssistantConversation,AssistantFeedbackCategory,AssistantMessage } from '@/types';

const categories:AssistantFeedbackCategory[]=['helpful','inaccurate','unsupported','stale','confusing','missing_evidence'];
export default function AssistantEvidence(){
  const{conversationId,messageId}=useLocalSearchParams<{conversationId:string;messageId:string}>();const{token}=useAuth();const[message,setMessage]=useState<AssistantMessage|null>(null);const[category,setCategory]=useState<AssistantFeedbackCategory>('unsupported');const[comment,setComment]=useState('');const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const load=useCallback(async()=>{if(!token||!conversationId)return;try{const c=await apiRequest<AssistantConversation>(`/assistant/conversations/${conversationId}`,{},token);setMessage(c.messages.find(x=>x.id===messageId)??null);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load evidence.');}},[conversationId,messageId,token]);useFocusEffect(useCallback(()=>{void load();},[load]));
  async function report(){if(!token||!message)return;try{await apiRequest(`/assistant/messages/${message.id}/feedback`,{method:'POST',body:JSON.stringify({category,comment:comment.trim()||null})},token);setNotice('Report added to your private review inbox. It did not create or change any financial action.');setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not report response.');}}
  if(!message)return <Screen><Text style={ui.title}>Assistant evidence</Text>{error?<Text style={ui.error}>{error}</Text>:<ActivityIndicator/>}</Screen>;
  const response=message.response;return <Screen><Text style={ui.title}>Assistant evidence and limitations</Text><Text style={ui.subtitle}>Response mode: {response?.mode??'unavailable'}. Generated wording is not independently verified.</Text>{error?<Text style={ui.error}>{error}</Text>:null}{notice?<Text style={ui.success}>{notice}</Text>:null}<Text style={ui.heading}>Freshness and uncertainty</Text>{response?.freshness.map(x=><Text key={x}>{x}</Text>)}<Text style={ui.heading}>Citations</Text>{response?.citations.length===0?<Text style={ui.muted}>No evidence was available; the response should abstain.</Text>:response?.citations.map((c,i)=><View style={ui.card} key={`${c.record_id}-${i}`}><Text style={ui.cardTitle}>[{i+1}] {c.source_type} · {c.freshness}</Text><Text>{c.excerpt}</Text><Text style={ui.muted}>{c.date?new Date(c.date).toLocaleString():'Undated'} · {c.record_id}</Text><ActionButton title="Open source record" onPress={()=>router.push(c.record_path as never)}/></View>)}<Text style={ui.heading}>Deterministic evidence references</Text>{response?.evidence_references.length===0?<Text style={ui.muted}>No stored calculation was used.</Text>:response?.evidence_references.map((x,i)=><View style={ui.card} key={i}><Text>{JSON.stringify(x,null,2)}</Text></View>)}<Text style={ui.heading}>Limitations</Text>{response?.limitations.map(x=><Text style={ui.muted} key={x}>• {x}</Text>)}<Text style={ui.heading}>Report response</Text><View style={ui.row}>{categories.map(x=><Choice key={x} label={x.replaceAll('_',' ')} selected={category===x} onPress={()=>setCategory(x)}/>)}</View><Field label="Optional note (maximum 500 characters)" value={comment} onChangeText={setComment} maxLength={500} multiline/><ActionButton title="Add to private review inbox" onPress={()=>void report()}/><ActionButton title="Open feedback history and review" onPress={()=>router.push('/assistant-feedback' as never)}/><Text style={ui.muted}>Your note may contain sensitive information. Keep it brief. Feedback never authorizes an action, changes a calculation, retrains a model, or changes provider settings.</Text></Screen>;
}
