import { useFocusEffect } from 'expo-router';
import { useCallback,useState } from 'react';
import { ActivityIndicator,Text,View } from 'react-native';
import { ApiError,apiRequest } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton,Field,Screen,ui } from '@/components';
import { AssistantFeedback,FeedbackFixtureExport } from '@/types';

export default function AssistantFeedbackScreen(){
  const{token}=useAuth();const[rows,setRows]=useState<AssistantFeedback[]>([]);const[notes,setNotes]=useState<Record<string,string>>({});const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[confirming,setConfirming]=useState(false);
  const load=useCallback(async()=>{if(!token)return;setLoading(true);try{const result=await apiRequest<AssistantFeedback[]>('/assistant/feedback',{},token);setRows(result);setNotes(Object.fromEntries(result.map(x=>[x.id,x.review_note??''])));setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load feedback history.');}finally{setLoading(false);}},[token]);useFocusEffect(useCallback(()=>{void load();},[load]));
  async function update(row:AssistantFeedback,body:Record<string,unknown>){if(!token)return;try{await apiRequest(`/assistant/feedback/${row.id}`,{method:'PUT',body:JSON.stringify(body)},token);setNotice('Feedback review updated. No financial record or model setting changed.');setConfirming(false);await load();}catch(e){setError(e instanceof ApiError?e.message:'Could not update feedback.');}}
  async function remove(row:AssistantFeedback){if(!token)return;try{await apiRequest(`/assistant/feedback/${row.id}`,{method:'DELETE'},token);setNotice('Feedback deleted.');setConfirming(false);await load();}catch(e){setError(e instanceof ApiError?e.message:'Could not delete feedback.');}}
  async function exportSelected(){if(!token)return;const ids=rows.filter(x=>x.status==='reviewed'&&x.fixture_selected).map(x=>x.id);if(!ids.length){setError('Review and select at least one report first.');return;}try{const result=await apiRequest<FeedbackFixtureExport>('/assistant/feedback/export',{method:'POST',body:JSON.stringify({feedback_ids:ids,confirm_sanitized_export:true})},token);setNotice(`${result.cases.length} sanitized case${result.cases.length===1?'':'s'} exported for manual regression-test implementation. Nothing was trained or changed automatically.`);setConfirming(false);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not export selected feedback.');}}
  return <Screen><Text style={ui.title}>Feedback history and review</Text><Text style={ui.subtitle}>This is your private personal review inbox. There is no administrator role. Feedback never authorizes financial action, changes calculations, retrains a model, edits prompts, or changes provider settings.</Text>{error?<Text style={ui.error}>{error}</Text>:null}{notice?<Text style={ui.success}>{notice}</Text>:null}{loading?<ActivityIndicator/>:null}{!loading&&rows.length===0?<Text style={ui.muted}>No assistant responses have been reported.</Text>:rows.map(row=><View style={ui.card} key={row.id}><Text style={ui.cardTitle}>{row.category.replaceAll('_',' ')} · {row.status}</Text><Text>{new Date(row.created_at).toLocaleString()} · {row.response_mode}</Text>{row.comment?<Text>{row.comment}</Text>:<Text style={ui.muted}>No optional note.</Text>}<Text style={ui.muted}>Citations: {row.citation_ids.length}; sources dated: {row.source_dates.length}; freshness: {row.freshness.join(', ')||'none'}</Text><Field label="Personal review annotation (maximum 500 characters)" value={notes[row.id]??''} onChangeText={value=>setNotes(x=>({...x,[row.id]:value}))} maxLength={500} multiline/><ActionButton title="Mark reviewed" onPress={()=>void update(row,{status:'reviewed',review_note:notes[row.id]?.trim()||null})}/><ActionButton title="Dismiss report" onPress={()=>void update(row,{status:'dismissed',review_note:notes[row.id]?.trim()||null})}/><ActionButton title={row.fixture_selected?'Remove from fixture selection':'Select for sanitized fixture export'} disabled={row.status!=='reviewed'} onPress={()=>void update(row,{fixture_selected:!row.fixture_selected})}/><ActionButton title="Delete feedback" onPress={()=>void remove(row)}/></View>)}<Text style={ui.heading}>Sanitized regression export</Text><Text style={ui.muted}>The export omits prompts, answers, names, record IDs, balances, account numbers, raw passages, comments, annotations, and provider secrets. It contains behavioral labels and evidence metadata for manual test design.</Text>{confirming?<><Text style={ui.error}>Confirm that the selected reviewed reports may be exported in sanitized form. This creates no test automatically and performs no training.</Text><ActionButton title="Confirm sanitized fixture export" onPress={()=>void exportSelected()}/><ActionButton title="Cancel export" onPress={()=>setConfirming(false)}/></>:<ActionButton title="Review fixture privacy and continue" onPress={()=>setConfirming(true)}/>}</Screen>;
}
