import * as DocumentPicker from 'expo-document-picker'; import { useFocusEffect } from 'expo-router';
import { useCallback,useState } from 'react'; import { Text,View } from 'react-native';
import { ApiError,apiRequest } from '@/api'; import { useAuth } from '@/auth'; import { ActionButton,Choice,Field,Screen,ui } from '@/components'; import { Book,BookPassage,Decision } from '@/types';
export default function BooksScreen(){const{token}=useAuth();const[books,setBooks]=useState<Book[]>([]);const[decisions,setDecisions]=useState<Decision[]>([]);const[title,setTitle]=useState('');const[author,setAuthor]=useState('');const[topic,setTopic]=useState('');const[source,setSource]=useState('Owned copy');const[file,setFile]=useState<DocumentPicker.DocumentPickerAsset|null>(null);const[q,setQ]=useState('');const[results,setResults]=useState<BookPassage[]>([]);const[decisionId,setDecisionId]=useState('');const[error,setError]=useState('');const[msg,setMsg]=useState('');
const refresh=useCallback(async()=>{if(!token)return;try{const[b,d]=await Promise.all([apiRequest<Book[]>('/books',{},token),apiRequest<Decision[]>('/decisions',{},token)]);setBooks(b);setDecisions(d);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load library.');}},[token]);useFocusEffect(useCallback(()=>{void refresh();},[refresh]));
async function pick(){const r=await DocumentPicker.getDocumentAsync({type:['text/plain','application/pdf','application/epub+zip'],copyToCacheDirectory:true});if(!r.canceled)setFile(r.assets[0]);}
async function upload(){if(!token||!file){setError('Select a TXT, EPUB, or PDF file.');return;}const form=new FormData();form.append('title',title);form.append('author',author);form.append('topic',topic);form.append('source',source);form.append('language','en');form.append('file',{uri:file.uri,name:file.name,type:file.mimeType||'application/octet-stream'} as unknown as Blob);try{const b=await apiRequest<Book>('/books',{method:'POST',body:form},token);setMsg(b.ingestion_status==='ocr_required'?'Scanned PDF detected. OCR is not supported.':'Book processed privately.');setFile(null);await refresh();}catch(e){setError(e instanceof ApiError?e.message:'Upload failed.');}}
async function search(){if(!token)return;try{setResults(await apiRequest<BookPassage[]>(`/book-search?q=${encodeURIComponent(q)}`,{},token));setError('');}catch(e){setError(e instanceof ApiError?e.message:'Search failed.');}}
async function attach(p:BookPassage){if(!token||!decisionId){setError('Choose a decision first.');return;}try{await apiRequest(`/decisions/${decisionId}/passages/${p.id}`,{method:'POST',body:JSON.stringify({note:'Selected learning support passage'})},token);setMsg('Passage attached as learning support. It does not affect decision scoring.');}catch(e){setError(e instanceof ApiError?e.message:'Could not attach passage.');}}
return <Screen><Text style={ui.title}>Personal financial book library</Text><Text style={ui.subtitle}>Educational context only. Passages are not market data or buy/sell instructions, and no order is placed.</Text>{error?<Text style={ui.error}>{error}</Text>:null}{msg?<Text style={ui.success}>{msg}</Text>:null}<Field label="Title" value={title} onChangeText={setTitle}/><Field label="Author" value={author} onChangeText={setAuthor}/><Field label="Topic" value={topic} onChangeText={setTopic}/><Field label="Source / authorization" value={source} onChangeText={setSource}/><ActionButton title={file?`Selected: ${file.name}`:'Select TXT, EPUB, or PDF'} onPress={()=>void pick()}/><ActionButton title="Upload and process privately" onPress={()=>void upload()}/><Text style={ui.heading}>Books</Text>{books.length===0?<Text style={ui.muted}>No books registered.</Text>:books.map(b=><View style={ui.card} key={b.id}><Text style={ui.cardTitle}>{b.title}</Text><Text>{b.author}</Text><Text>Status: {b.ingestion_status}</Text>{b.status_detail?<Text style={ui.muted}>{b.status_detail}</Text>:null}</View>)}<Text style={ui.heading}>Search cited passages</Text><Field label="Search" value={q} onChangeText={setQ}/><ActionButton title="Search library" onPress={()=>void search()}/>{results.length===0&&q?<Text style={ui.muted}>No matching passages.</Text>:null}<Text style={ui.muted}>Attach learning support to decision:</Text><View style={ui.row}>{decisions.map(d=><Choice key={d.id} label={`${d.instrument} ${d.action_considered}`} selected={decisionId===d.id} onPress={()=>setDecisionId(d.id)}/>)}</View>{results.map(p=><View style={ui.card} key={p.id}><Text style={ui.cardTitle}>{p.book_title} — {p.reference_label}</Text><Text>{p.excerpt}</Text><Text style={ui.muted}>Citation: {p.author}, {p.reference_type} {p.reference_label}. Short excerpt; learning support only.</Text><ActionButton title="Attach citation to decision" onPress={()=>void attach(p)}/></View>)}</Screen>}
