import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { ApiError, apiRequest, newIdempotencyKey } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton, Choice, Field, Screen, ui } from '@/components';
import { MarketplaceOutcome, OpportunityAnalysis } from '@/types';

export default function Inventory(){
  const{token}=useAuth(); const[rows,setRows]=useState<MarketplaceOutcome[]>([]); const[estimates,setEstimates]=useState<OpportunityAnalysis[]>([]); const[analysisId,setAnalysisId]=useState('');
  const[purchased,setPurchased]=useState('');const[purchaseCost,setPurchaseCost]=useState('');const[other,setOther]=useState('0');const[sold,setSold]=useState('');const[revenue,setRevenue]=useState('');const[fees,setFees]=useState('0');const[returned,setReturned]=useState('0');const[returnCosts,setReturnCosts]=useState('0');const[remaining,setRemaining]=useState('0');const[error,setError]=useState('');
  const refresh=useCallback(async()=>{if(token)try{const[o,a]=await Promise.all([apiRequest<MarketplaceOutcome[]>('/marketplace/outcomes',{},token),apiRequest<OpportunityAnalysis[]>('/marketplace/analyses',{},token)]);setRows(o);setEstimates(a);if(!analysisId&&a[0])setAnalysisId(a[0].id);}catch(e){setError(e instanceof ApiError?e.message:'Could not load outcomes.');}},[token,analysisId]);
  useFocusEffect(useCallback(()=>{void refresh();},[refresh]));
  async function save(){if(!token)return;try{await apiRequest('/marketplace/outcomes',{method:'POST',headers:{'Idempotency-Key':newIdempotencyKey()},body:JSON.stringify({analysis_id:analysisId,recorded_at:new Date().toISOString(),purchased_quantity:purchased,actual_purchase_cost:purchaseCost,actual_other_costs:other,sold_quantity:sold,actual_sales_revenue:revenue,actual_sales_fees:fees,returned_quantity:returned,return_costs:returnCosts,remaining_quantity:remaining,notes:'Transactions completed outside the app'})},token);setError('');await refresh();}catch(e){setError(e instanceof ApiError?e.message:'Could not record outcome.');}}
  return <Screen><Text style={ui.title}>Resale inventory and outcomes</Text><Text style={ui.subtitle}>Manually record transactions completed outside the app. This screen cannot purchase goods or create marketplace listings.</Text>{error?<Text style={ui.error}>{error}</Text>:null}<Text style={ui.heading}>Original estimate</Text>{estimates.length===0?<Text style={ui.muted}>Create a marketplace estimate first.</Text>:<View style={ui.row}>{estimates.map(x=><Choice key={x.id} label={`${x.calculated_metrics.net_margin_per_unit??'Unavailable'} PKR net/unit`} selected={analysisId===x.id} onPress={()=>setAnalysisId(x.id)}/>)}</View>}<Field label="Purchased quantity" value={purchased} onChangeText={setPurchased}/><Field label="Actual purchase cost (PKR total)" value={purchaseCost} onChangeText={setPurchaseCost}/><Field label="Other actual costs" value={other} onChangeText={setOther}/><Field label="Sold quantity" value={sold} onChangeText={setSold}/><Field label="Sales revenue" value={revenue} onChangeText={setRevenue}/><Field label="Sales fees" value={fees} onChangeText={setFees}/><Field label="Returned quantity" value={returned} onChangeText={setReturned}/><Field label="Return costs" value={returnCosts} onChangeText={setReturnCosts}/><Field label="Remaining stock" value={remaining} onChangeText={setRemaining}/><ActionButton title="Record completed outside-app outcome" onPress={()=>void save()}/><Text style={ui.heading}>Outcome history</Text>{rows.length===0?<Text style={ui.muted}>No outcomes recorded.</Text>:rows.map(x=><View style={ui.card} key={x.id}><Text style={ui.cardTitle}>Actual net result: {x.actual_net_result} PKR</Text><Text>Forecast error: {x.forecast_error??'unavailable'} PKR</Text><Text>Remaining: {x.remaining_quantity}</Text><Text style={ui.muted}>No success label is assigned. Review the calculation and assumption differences.</Text></View>)}</Screen>;
}
