import {useCallback,useState} from 'react';
import {Text,View} from 'react-native';
import {useFocusEffect} from 'expo-router';
import {ActionButton,Screen,ui} from '@/components';
import {apiRequest,ApiError} from '@/api';
import {useAuth} from '@/auth';
import {registerPush} from '@/notifications';
import {NotificationDelivery,NotificationDevice,NotificationEventType,NotificationPreference} from '@/types';

const events:NotificationEventType[]=['reminder_due','assistant_response_ready','feedback_review_status_changed'];
export default function NotificationSettings(){
  const{token}=useAuth();const[devices,setDevices]=useState<NotificationDevice[]>([]);const[prefs,setPrefs]=useState<NotificationPreference[]>([]);const[history,setHistory]=useState<NotificationDelivery[]>([]);const[error,setError]=useState('');const[notice,setNotice]=useState('');
  const refresh=useCallback(async()=>{if(!token)return;try{const[d,p,h]=await Promise.all([apiRequest<NotificationDevice[]>('/notifications/devices',{},token),apiRequest<NotificationPreference[]>('/notifications/preferences',{},token),apiRequest<NotificationDelivery[]>('/notifications/history',{},token)]);setDevices(d);setPrefs(p);setHistory(h);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load notification settings.');}},[token]);
  useFocusEffect(useCallback(()=>{void refresh()},[refresh]));
  async function setup(){if(!token)return;try{await registerPush(token);setNotice('Push token registered. Notifications remain off until you enable this device and event types.');await refresh();}catch(e){setError(e instanceof Error?e.message:'Push registration failed.');}}
  async function deviceEnabled(d:NotificationDevice,enabled:boolean){if(!token)return;try{await apiRequest(`/notifications/devices/${d.id}`,{method:'PUT',body:JSON.stringify({notifications_enabled:enabled})},token);await refresh();}catch(e){setError(e instanceof ApiError?e.message:'Could not update device.');}}
  async function pref(event_type:NotificationEventType,enabled:boolean,device_id?:string){if(!token)return;await apiRequest('/notifications/preferences',{method:'PUT',body:JSON.stringify({event_type,enabled,device_id:device_id||null})},token);await refresh();}
  async function revoke(id:string){if(!token)return;await apiRequest(`/notifications/devices/${id}`,{method:'DELETE'},token);setNotice('Device revoked. Its device-bound sign-in is invalid and it will receive no future fanout.');await refresh();}
  return <Screen><Text style={ui.title}>Notifications and devices</Text><Text style={ui.subtitle}>All notification types are opt-in. Lock-screen messages are generic and contain no balances, holdings, tax data, passages, or assistant answers.</Text>{error?<Text style={ui.error}>{error}</Text>:null}{notice?<Text style={ui.success}>{notice}</Text>:null}<ActionButton title="Register this physical device" onPress={()=>void setup()}/><Text style={ui.muted}>Remote push requires a development build, device permission, an EAS project ID, and configured Android/iOS credentials. Expo acceptance does not prove a device displayed a notification.</Text><Text style={ui.heading}>User event preferences</Text>{events.map(e=>{const enabled=prefs.find(x=>x.event_type===e)?.enabled??false;return <View style={ui.card} key={e}><Text style={ui.cardTitle}>{e.replaceAll('_',' ')}</Text><ActionButton title={enabled?'Disable for user':'Enable for user'} onPress={()=>void pref(e,!enabled)}/></View>})}<Text style={ui.heading}>Registered devices</Text>{devices.length===0?<Text style={ui.muted}>No registered devices.</Text>:devices.map(d=><View style={ui.card} key={d.id}><Text style={ui.cardTitle}>{d.display_name} · {d.platform}</Text><Text>Status: {d.push_status} · last seen {new Date(d.last_seen_at).toLocaleString()}</Text><ActionButton title={d.notifications_enabled?'Disable device':'Enable device'} onPress={()=>void deviceEnabled(d,!d.notifications_enabled)} disabled={d.push_status==='revoked'}/>{events.map(e=><ActionButton key={e} title={`${d.preferences[e]?'Disable':'Enable'} ${e.replaceAll('_',' ')}`} onPress={()=>void pref(e,!d.preferences[e],d.id)} disabled={d.push_status==='revoked'}/>)}<ActionButton title="Revoke device and session" onPress={()=>void revoke(d.id)} disabled={d.push_status==='revoked'}/></View>)}<Text style={ui.heading}>Delivery history</Text>{history.length===0?<Text style={ui.muted}>No notification deliveries.</Text>:history.map(h=><View style={ui.card} key={h.id}><Text>{h.event_type.replaceAll('_',' ')} · {h.status}</Text><Text style={ui.muted}>{new Date(h.created_at).toLocaleString()} · attempts {h.attempt_count}{h.last_error_code?` · ${h.last_error_code}`:''}</Text></View>)}</Screen>
}
