import { useFocusEffect } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { ApiError, apiRequest, newIdempotencyKey } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton, Choice, Field, Screen, ui } from '@/components';
import { OpportunityAnalysis, PropertyListing } from '@/types';

const units = ['sq_ft','sq_yd','marla_225_sq_ft','marla_272_25_sq_ft','kanal_4500_sq_ft','kanal_5445_sq_ft'] as const;
export default function PropertyScreen(){
  const {token}=useAuth(); const [items,setItems]=useState<PropertyListing[]>([]); const [error,setError]=useState(''); const [message,setMessage]=useState('');
  const [source,setSource]=useState('User research'); const [url,setUrl]=useState(''); const [purpose,setPurpose]=useState<'sale'|'rent'>('sale'); const [propertyType,setPropertyType]=useState('Apartment'); const [areaName,setAreaName]=useState('Clifton'); const [area,setArea]=useState('1000'); const [unit,setUnit]=useState<typeof units[number]>('sq_ft'); const [asking,setAsking]=useState('');
  const [analysis,setAnalysis]=useState<OpportunityAnalysis|null>(null); const [purchase,setPurchase]=useState(''); const [rent,setRent]=useState(''); const [expenses,setExpenses]=useState(''); const [tax,setTax]=useState('');
  const refresh=useCallback(async()=>{if(!token)return;try{setItems(await apiRequest<PropertyListing[]>('/opportunities/karachi-real-estate/listings',{},token));setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load listings.');}},[token]);
  useFocusEffect(useCallback(()=>{void refresh();},[refresh]));
  async function add(){if(!token)return;try{await apiRequest('/opportunities/karachi-real-estate/listings',{method:'POST',headers:{'Idempotency-Key':newIdempotencyKey()},body:JSON.stringify({city:'Karachi',source_type:'user_entered',source_name:source,canonical_url:url||null,observed_at:new Date().toISOString(),purpose,property_type:propertyType,area_name:areaName,area_amount:area,area_unit:unit,asking_amount:asking,attributes:{}})},token);setMessage('Listing saved as user-entered research. No website was fetched.');setError('');await refresh();}catch(e){setError(e instanceof ApiError?e.message:'Could not save listing.');}}
  async function compare(){if(!token)return;try{const r=await apiRequest<OpportunityAnalysis>('/opportunities/analyze/karachi_real_estate/comparables',{method:'POST',headers:{'Idempotency-Key':newIdempotencyKey()},body:JSON.stringify({area_name:areaName,property_type:propertyType,purpose,area_min:area,area_max:area,area_unit:unit})},token);setAnalysis(r);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Comparable analysis failed.');}}
  async function calculateYield(){if(!token)return;try{const body:Record<string,unknown>={purchase_price:purchase,monthly_rent:rent};if(expenses)body.annual_expenses={user_supplied_other_costs:expenses};if(tax)body.annual_property_tax=tax;setAnalysis(await apiRequest<OpportunityAnalysis>('/opportunities/analyze/karachi_real_estate/yield',{method:'POST',headers:{'Idempotency-Key':newIdempotencyKey()},body:JSON.stringify(body)},token));setError('');}catch(e){setError(e instanceof ApiError?e.message:'Yield estimate failed.');}}
  return <Screen><Text style={ui.title}>Karachi property research</Text><Text style={ui.subtitle}>Research estimates from data you enter or are authorized to use. URLs are stored as provenance and never crawled. Asking prices are unverified and are not transaction prices.</Text>{error?<Text style={ui.error}>{error}</Text>:null}{message?<Text style={ui.success}>{message}</Text>:null}<Text style={ui.heading}>Add listing</Text><Field label="Source name" value={source} onChangeText={setSource}/><Field label="Source URL (optional)" value={url} onChangeText={setUrl} autoCapitalize="none"/><View style={ui.row}>{(['sale','rent'] as const).map(x=><Choice key={x} label={x} selected={purpose===x} onPress={()=>setPurpose(x)}/>)}</View><Field label="Property type" value={propertyType} onChangeText={setPropertyType}/><Field label="Karachi area" value={areaName} onChangeText={setAreaName}/><Field label="Area amount" value={area} onChangeText={setArea} keyboardType="decimal-pad"/><Text style={ui.muted}>Choose an explicit unit; “marla” alone is not accepted.</Text><View style={ui.row}>{units.map(x=><Choice key={x} label={x} selected={unit===x} onPress={()=>setUnit(x)}/>)}</View><Field label="Unverified asking amount (PKR)" value={asking} onChangeText={setAsking} keyboardType="decimal-pad"/><ActionButton title="Save research listing" onPress={()=>void add()}/><ActionButton title="Analyze exact-size comparables" onPress={()=>void compare()}/><Text style={ui.heading}>Listings</Text>{items.length===0?<Text style={ui.muted}>No listing data. Add authorized research above.</Text>:items.map(x=><View style={ui.card} key={x.id}><Text style={ui.cardTitle}>{x.property_type} · {x.area_name}</Text><Text>{x.area_amount} {x.area_unit} · {x.asking_amount} PKR</Text><Text style={ui.muted}>{x.source_name} · observed {new Date(x.observed_at).toLocaleDateString()} · {x.asking_price_status}{x.stale?' · STALE':''}</Text></View>)}<Text style={ui.heading}>Rental-yield estimate</Text><Field label="Purchase price (PKR)" value={purchase} onChangeText={setPurchase} keyboardType="decimal-pad"/><Field label="Monthly rent (PKR)" value={rent} onChangeText={setRent} keyboardType="decimal-pad"/><Field label="Annual other costs (optional, PKR)" value={expenses} onChangeText={setExpenses} keyboardType="decimal-pad"/><Field label="Annual property tax assumption (optional, PKR)" value={tax} onChangeText={setTax} keyboardType="decimal-pad"/><ActionButton title="Calculate estimate" onPress={()=>void calculateYield()}/>{analysis?<View style={ui.card}><Text style={ui.cardTitle}>{analysis.analysis_type} estimate</Text><Text>{JSON.stringify(analysis.calculated_metrics,null,2)}</Text>{analysis.limitations.map(x=><Text style={ui.muted} key={x}>• {x}</Text>)}<Text style={ui.muted}>Estimate only. No recommendation, offer, or order is created.</Text></View>:<Text style={ui.muted}>No analysis calculated. Comparable results may report insufficient data.</Text>}</Screen>;
}
