import json,uuid
from datetime import datetime,timedelta,timezone
from fastapi.testclient import TestClient
from sqlalchemy import func,select
from app.database import SessionLocal
from app.main import app
from app.models import MarketplaceProduct,MarketplaceProductObservation
client=TestClient(app);BASE="/api/v1/marketplace";PASSWORD="correct horse battery staple"
def auth(label):
 r=client.post("/auth/register",json={"email":f"{label}-{uuid.uuid4()}@example.com","password":PASSWORD});return {"Authorization":f"Bearer {r.json()['token']['access_token']}"}
def product(h,name="Wireless Earbuds",**kw):
 body={"normalized_name":name,"brand":"Acme","model":"TWS Pro","category":"Audio","canonical_attributes":{}};body.update(kw);r=client.post(f"{BASE}/products",headers=h,json=body);assert r.status_code==201,r.text;return r.json()
def observe(h,p,name="Wireless Earbuds",when=None):
 r=client.post(f"{BASE}/products/{p['id']}/observations",headers=h,json={"marketplace":"Daraz","source_type":"user_entered","source_reference":str(uuid.uuid4()),"observed_name":name,"observed_price":"1500","currency_code":"PKR","observed_at":when or datetime.now(timezone.utc).isoformat(),"raw_attributes":{},"evidence":{"note":"manual"}});assert r.status_code==201,r.text;return r.json()
def upload(h,content,name="items.csv",kind="product_observations",mime="text/csv"):
 return client.post(f"{BASE}/imports",headers=h,data={"import_type":kind,"source_classification":"authorized_export"},files={"file":(name,content,mime)})

def test_csv_review_preview_mapping_commit_and_duplicate_detection():
 h=auth("import-csv");p=product(h);csv_data=f"product,marketplace,price,currency,observation_date,source\n{p['normalized_name']},Daraz,1600.25,PKR,{datetime.now(timezone.utc).isoformat()},authorized.csv\n"
 created=upload(h,csv_data);assert created.status_code==201,created.text;bid=created.json()["id"];assert created.json()["committed_rows"]==0
 preview=client.get(f"{BASE}/imports/{bid}/preview",headers=h).json();assert preview["rows"][0]["duplicate_status"] in ("exact_match","probable_match");row=preview["rows"][0];assert row["action"]=="attach_to_existing_product"
 committed=client.post(f"{BASE}/imports/{bid}/commit",headers=h);assert committed.status_code==200,committed.text;assert committed.json()["committed_rows"]==1;assert len(client.get(f"{BASE}/products/{p['id']}/observations",headers=h).json())==1
def test_json_mapping_review_probable_requires_explicit_action():
 h=auth("import-json");p=product(h);raw=[{"title":"TWS Pro Wireless Earbuds","market":"Daraz","amount":"1700","ccy":"PKR","date":datetime.now(timezone.utc).isoformat(),"ref":"json export"}];created=upload(h,json.dumps(raw),"items.json","product_observations","application/json");bid=created.json()["id"]
 mapping={"observed_name":"title","marketplace":"market","observed_price":"amount","currency_code":"ccy","observed_at":"date","source_reference":"ref"};mapped=client.post(f"{BASE}/imports/{bid}/mapping",headers=h,json={"mapping":mapping});assert mapped.status_code==200;row=client.get(f"{BASE}/imports/{bid}/preview",headers=h).json()["rows"][0];assert row["action"] in ("requires_review","attach_to_existing_product")
 if row["action"]=="requires_review":assert client.post(f"{BASE}/imports/{bid}/commit",headers=h).status_code==422;assert client.put(f"{BASE}/imports/{bid}/rows/{row['id']}",headers=h,json={"action":"attach_to_existing_product","proposed_product_id":p["id"]}).status_code==200
 assert client.post(f"{BASE}/imports/{bid}/commit",headers=h).status_code==200
def test_invalid_files_decimal_currency_limits_and_cancel(monkeypatch):
 h=auth("import-invalid");assert upload(h,"not json","bad.json","product_observations","application/json").status_code==422;assert upload(h,"x","bad.exe","product_observations","application/octet-stream").status_code==415
 bad=f"product,supplier,source_channel,unit_cost,currency,observed_date\nThing,S,local_wholesaler,nope,USD,{datetime.now(timezone.utc).isoformat()}\n";r=upload(h,bad,"bad.csv","sourcing_options");assert r.status_code==201;preview=client.get(f"{BASE}/imports/{r.json()['id']}/preview",headers=h).json();assert preview["rows"][0]["validation_status"]=="invalid";assert client.post(f"{BASE}/imports/{r.json()['id']}/cancel",headers=h).json()["status"]=="cancelled"
def test_import_commit_is_all_or_nothing_when_unresolved():
 h=auth("import-rollback");csv_data=f"product,marketplace,price,currency,observation_date,source\nNew A,Daraz,1000,PKR,{datetime.now(timezone.utc).isoformat()},x\nBad,Daraz,nope,PKR,{datetime.now(timezone.utc).isoformat()},x\n";b=upload(h,csv_data).json();before=client.get(f"{BASE}/products",headers=h).json();assert client.post(f"{BASE}/imports/{b['id']}/commit",headers=h).status_code==422;assert client.get(f"{BASE}/products",headers=h).json()==before

def test_merge_archives_source_moves_evidence_watchlist_and_preserves_ranking_history():
 h=auth("merge");source=product(h,"AirPods Pro 2",model="A");target=product(h,"Apple AirPods Pro 2nd Gen",model="B");obs=observe(h,source);client.post(f"{BASE}/watchlist",headers=h,json={"product_id":source["id"],"notes":"source"});client.post(f"{BASE}/products/{source['id']}/rank",headers=h,json={});before=len(client.get(f"{BASE}/rankings",headers=h).json());merged=client.post(f"{BASE}/products/merge",headers=h,json={"source_product_id":source["id"],"target_product_id":target["id"],"reason":"same model"});assert merged.status_code==200,merged.text;assert client.get(f"{BASE}/products/{target['id']}/observations",headers=h).json()[0]["id"]==obs["id"];assert len(client.get(f"{BASE}/rankings",headers=h).json())==before;assert client.get(f"{BASE}/watchlist",headers=h).json()[0]["product_id"]==target["id"];assert any(x["type"]=="merge" for x in client.get(f"{BASE}/products/{target['id']}/history",headers=h).json())
def test_merge_cross_user_and_split_selected_observations_with_audit():
 a,b=auth("split-a"),auth("split-b");p=product(a);o1=observe(a,p,"Model One");o2=observe(a,p,"Model Two");foreign=product(b);assert client.post(f"{BASE}/products/merge",headers=a,json={"source_product_id":p["id"],"target_product_id":foreign["id"]}).status_code==404
 split=client.post(f"{BASE}/products/{p['id']}/split",headers=a,json={"new_product":{"normalized_name":"Model Two","brand":"Acme","model":"Two","category":"Audio","canonical_attributes":{}},"observation_ids":[o2["id"]],"sourcing_ids":[],"competition_ids":[],"reason":"different model"});assert split.status_code==201,split.text;new_id=split.json()["new_product_id"];assert len(client.get(f"{BASE}/products/{p['id']}/observations",headers=a).json())==1;assert client.get(f"{BASE}/products/{new_id}/observations",headers=a).json()[0]["id"]==o2["id"];assert any(x["type"]=="split" for x in client.get(f"{BASE}/products/{new_id}/history",headers=a).json())
def test_preset_crud_validation_ownership_and_run():
 a,b=auth("preset-a"),auth("preset-b");product(a,"Cable",category="Accessories");payload={"name":"High Margin Daraz","filters":{"category":"Accessories"},"sorting":{"field":"research_score","direction":"desc"},"is_default":True};created=client.post(f"{BASE}/research-presets",headers=a,json=payload);assert created.status_code==201,created.text;pid=created.json()["id"];assert client.get(f"{BASE}/research-presets",headers=b).json()==[];run=client.post(f"{BASE}/research-presets/{pid}/run",headers=a);assert run.status_code==200;assert len(run.json()["results"])==1;assert client.put(f"{BASE}/research-presets/{pid}",headers=b,json=payload).status_code==404;assert client.post(f"{BASE}/research-presets",headers=a,json={**payload,"name":"bad","filters":{"sql":"drop"}}).status_code==422;assert client.delete(f"{BASE}/research-presets/{pid}",headers=a).status_code==204
def test_freshness_quality_states_and_batch_ranking_partial_failure():
 h=auth("quality");p=product(h);fresh=observe(h,p,when=(datetime.now(timezone.utc)-timedelta(days=2)).isoformat());aging=observe(h,p,when=(datetime.now(timezone.utc)-timedelta(days=10)).isoformat());stale=observe(h,p,when=(datetime.now(timezone.utc)-timedelta(days=20)).isoformat());rows=client.get(f"{BASE}/products/{p['id']}/observations",headers=h).json();states={x["id"]:x["freshness_status"] for x in rows};assert states[fresh["id"]]=="fresh";assert states[aging["id"]]=="aging";assert states[stale["id"]]=="stale";q=client.get(f"{BASE}/products/{p['id']}/data-quality",headers=h).json();assert q["research_readiness"] in ("incomplete","stale");assert q["stale_evidence_count"]>=1
 result=client.post(f"{BASE}/rankings/batch",headers=h,json={"product_ids":[p["id"],str(uuid.uuid4())]});assert result.status_code==200;assert result.json()["partial_failures"]==1;assert client.post(f"{BASE}/rankings/batch",headers=h,json={"product_ids":[p["id"],p["id"]]}).status_code==422
def test_exports_are_user_scoped_and_csv_formula_safe():
 a,b=auth("export-a"),auth("export-b");product(a,"=DANGEROUS",brand="+brand",model="@model");product(b,"Private");data=client.get(f"{BASE}/exports/products?format=json",headers=a).json();assert len(data)==1;assert data[0]["name"]=="=DANGEROUS";csv_text=client.get(f"{BASE}/exports/products?format=csv",headers=a).text;assert "'=DANGEROUS" in csv_text;assert "'+brand" in csv_text;assert "'@model" in csv_text
