import { useFocusEffect, useLocalSearchParams } from 'expo-router';
import { useCallback, useState } from 'react';
import { Text, View } from 'react-native';
import { ApiError, apiRequest } from '@/api';
import { useAuth } from '@/auth';
import { ActionButton, Choice, Field, Screen, ui } from '@/components';
import { MarketplaceHistoryEvent } from '@/types';

type DetailData={product:{normalized_name:string};observations:Record<string,unknown>[];sourcing:Record<string,unknown>[];competition:Record<string,unknown>[];rankings:Record<string,unknown>[]};
const evidenceKinds=['price','sourcing','competition'] as const;
export default function Detail(){
  const{id}=useLocalSearchParams<{id:string}>(); const{token}=useAuth(); const[data,setData]=useState<DetailData|null>(null); const[history,setHistory]=useState<MarketplaceHistoryEvent[]>([]); const[quality,setQuality]=useState<Record<string,unknown>|null>(null); const[kind,setKind]=useState<typeof evidenceKinds[number]>('price'); const[value,setValue]=useState(''); const[reference,setReference]=useState(''); const[error,setError]=useState(''); const[message,setMessage]=useState('');
  const load=useCallback(async()=>{if(!token||!id)return;try{const[d,h,q]=await Promise.all([apiRequest<DetailData>(`/api/v1/marketplace/products/${id}`,{},token),apiRequest<MarketplaceHistoryEvent[]>(`/api/v1/marketplace/products/${id}/history`,{},token),apiRequest<Record<string,unknown>>(`/api/v1/marketplace/products/${id}/data-quality`,{},token)]);setData(d);setHistory(h);setQuality(q);setError('');}catch(e){setError(e instanceof ApiError?e.message:'Could not load intelligence.');}},[id,token]); useFocusEffect(useCallback(()=>{void load();},[load]));
  async function rank(){if(!token)return;try{await apiRequest(`/api/v1/marketplace/products/${id}/rank`,{method:'POST',body:'{}'},token);setMessage('Research Score snapshot recorded.');await load();}catch(e){setError(e instanceof ApiError?e.message:'Could not calculate score.');}}
  async function watch(){if(!token)return;try{await apiRequest('/api/v1/marketplace/watchlist',{method:'POST',body:JSON.stringify({product_id:id,notes:'Saved from product detail'})},token);setMessage('Added to watchlist.');}catch(e){setError(e instanceof ApiError?e.message:'Could not add watchlist item.');}}
  async function addEvidence(){if(!token||!value||!reference){setError('Enter a numeric value and source reference.');return;}const observed_at=new Date().toISOString();let path='observations';let body:Record<string,unknown>={marketplace:'Other',source_type:'user_entered',source_reference:reference,observed_name:data?.product.normalized_name??'Product',observed_price:value,currency_code:'PKR',observed_at,raw_attributes:{},evidence:{entered_in_mobile:true}};if(kind==='sourcing'){path='sourcing';body={source_type:'user_entered',source_channel:'other',source_reference:reference,unit_cost:value,currency_code:'PKR',observed_at,evidence:{entered_in_mobile:true}};}if(kind==='competition'){path='competition';body={source_type:'user_entered',source_reference:reference,comparable_listing_count:Number(value),observed_at,evidence:{entered_in_mobile:true}};}try{await apiRequest(`/api/v1/marketplace/products/${id}/${path}`,{method:'POST',body:JSON.stringify(body)},token);setValue('');setReference('');setMessage('Evidence saved with timestamp and provenance.');await load();}catch(e){setError(e instanceof ApiError?e.message:'Could not save evidence.');}}
  return <Screen><Text style={ui.title}>{data?.product.normalized_name??'Product intelligence'}</Text><Text style={ui.subtitle}>Karachi · PKR · research evidence only</Text>{error?<Text style={ui.error}>{error}</Text>:null}{message?<Text style={ui.success}>{message}</Text>:null}{!data?<Text style={ui.muted}>Loading or unavailable.</Text>:<><View style={ui.card}><Text style={ui.cardTitle}>Research readiness</Text><Text>{String(quality?.research_readiness??'unavailable')}</Text><Text>Missing: {Array.isArray(quality?.missing_fields)?quality.missing_fields.join(', '):'unavailable'}</Text><Text style={ui.muted}>Freshness and completeness affect confidence; missing values stay unavailable.</Text></View><View style={ui.card}><Text style={ui.cardTitle}>Evidence summary</Text><Text>{data.observations.length} price/demand observations</Text><Text>{data.sourcing.length} sourcing options</Text><Text>{data.competition.length} competition observations</Text><Text>{data.rankings.length} immutable ranking snapshots</Text></View></>}
  <Text style={ui.heading}>Add evidence</Text><View style={ui.row}>{evidenceKinds.map(x=><Choice key={x} label={x} selected={kind===x} onPress={()=>setKind(x)}/>)}</View><Field label={kind==='competition'?'Comparable listing count':kind==='sourcing'?'Unit cost (PKR)':'Observed price (PKR)'} value={value} onChangeText={setValue} keyboardType="decimal-pad"/><Field label="Source reference or note" value={reference} onChangeText={setReference}/><ActionButton title="Save timestamped evidence" onPress={()=>void addEvidence()}/><ActionButton title="Create explainable Research Score snapshot" onPress={()=>void rank()}/><ActionButton title="Add to watchlist" onPress={()=>void watch()}/>
  <Text style={ui.heading}>Audit history</Text>{history.length===0?<Text style={ui.muted}>No recorded history.</Text>:history.map((x,i)=><View style={ui.card} key={`${x.type}-${x.at}-${i}`}><Text style={ui.cardTitle}>{x.type.replaceAll('_',' ')}</Text><Text>{new Date(x.at).toLocaleString()}</Text><Text style={ui.muted}>{JSON.stringify(x.data)}</Text></View>)}</Screen>;
}
