"""Add marketplace resale research and outcome records.

Revision ID: 20260930_0008
Revises: 20260930_0007
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="20260930_0008";down_revision="20260930_0007";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("marketplace_listings",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("source_method",sa.String(30),nullable=False),sa.Column("source_platform",sa.String(30),nullable=False),sa.Column("product_name",sa.String(300),nullable=False),sa.Column("sku",sa.String(100)),sa.Column("source_listing_id",sa.String(200)),sa.Column("canonical_url",sa.String(1000)),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("source_price",sa.Numeric(18,4),nullable=False),sa.Column("attributes",sa.JSON(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("expected_karachi_selling_price",sa.Numeric(18,2)),sa.Column("local_sales_channel",sa.String(100)),sa.Column("information_quality",sa.String(30),nullable=False),sa.Column("confirmed_inventory_value",sa.Numeric(18,2)),sa.Column("inventory_valued_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("source_platform IN ('Daraz','Temu','SHEIN','Other')",name="ck_marketplace_listings_platform"),sa.CheckConstraint("source_price > 0",name="ck_marketplace_listings_price"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("id","user_id",name="uq_marketplace_listings_id_user_id"))
    op.create_index("ix_marketplace_listings_user_id","marketplace_listings",["user_id"]);op.create_index("ix_marketplace_listings_source_platform","marketplace_listings",["source_platform"]);op.create_index("ix_marketplace_listings_observed_at","marketplace_listings",["observed_at"])
    op.create_index("uq_marketplace_listings_user_url","marketplace_listings",["user_id","canonical_url"],unique=True,postgresql_where=sa.text("canonical_url IS NOT NULL"));op.create_index("uq_marketplace_listings_user_source_id","marketplace_listings",["user_id","source_platform","source_listing_id"],unique=True,postgresql_where=sa.text("source_listing_id IS NOT NULL"))
    op.create_table("marketplace_analyses",sa.Column("analysis_id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("listing_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("quantity",sa.Numeric(18,4),nullable=False),sa.Column("landed_cost_per_unit",sa.Numeric(18,4)),sa.Column("break_even_per_unit",sa.Numeric(18,4)),sa.Column("gross_margin_per_unit",sa.Numeric(18,4)),sa.Column("net_margin_per_unit",sa.Numeric(18,4)),sa.Column("inventory_cash_roi_percent",sa.Numeric(12,4)),sa.ForeignKeyConstraint(["analysis_id"],["opportunity_analyses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["listing_id","user_id"],["marketplace_listings.id","marketplace_listings.user_id"],ondelete="RESTRICT",name="fk_marketplace_analyses_listing_owner"))
    op.create_index("ix_marketplace_analyses_user_id","marketplace_analyses",["user_id"])
    op.create_table("marketplace_outcomes",sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("analysis_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("recorded_at",sa.DateTime(timezone=True),nullable=False),sa.Column("purchased_quantity",sa.Numeric(18,4),nullable=False),sa.Column("actual_purchase_cost",sa.Numeric(18,2),nullable=False),sa.Column("actual_other_costs",sa.Numeric(18,2),nullable=False),sa.Column("sold_quantity",sa.Numeric(18,4),nullable=False),sa.Column("actual_sales_revenue",sa.Numeric(18,2),nullable=False),sa.Column("actual_sales_fees",sa.Numeric(18,2),nullable=False),sa.Column("returned_quantity",sa.Numeric(18,4),nullable=False),sa.Column("return_costs",sa.Numeric(18,2),nullable=False),sa.Column("remaining_quantity",sa.Numeric(18,4),nullable=False),sa.Column("notes",sa.String(2000)),sa.Column("actual_net_result",sa.Numeric(18,2),nullable=False),sa.Column("forecast_error",sa.Numeric(18,2)),sa.Column("assumption_differences",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("purchased_quantity >= 0 AND sold_quantity >= 0 AND returned_quantity >= 0 AND remaining_quantity >= 0",name="ck_marketplace_outcomes_quantities"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["analysis_id"],["marketplace_analyses.analysis_id"],ondelete="RESTRICT"),sa.UniqueConstraint("id","user_id",name="uq_marketplace_outcomes_id_user_id"))
    op.create_index("ix_marketplace_outcomes_user_id","marketplace_outcomes",["user_id"]);op.create_index("ix_marketplace_outcomes_analysis_id","marketplace_outcomes",["analysis_id"])

def downgrade():
    op.drop_table("marketplace_outcomes");op.drop_table("marketplace_analyses");op.drop_index("uq_marketplace_listings_user_source_id",table_name="marketplace_listings");op.drop_index("uq_marketplace_listings_user_url",table_name="marketplace_listings");op.drop_table("marketplace_listings")
