"""Add marketplace reviewed imports and curation.

Revision ID: 20261001_0010
Revises: 20261001_0009
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20261001_0010";down_revision="20261001_0009";branch_labels=None;depends_on=None
U=postgresql.UUID(as_uuid=True)
def upgrade():
    op.add_column("marketplace_products",sa.Column("is_archived",sa.Boolean(),server_default="false",nullable=False));op.add_column("marketplace_products",sa.Column("merged_into_id",U));op.create_foreign_key("fk_marketplace_products_merged_into","marketplace_products","marketplace_products",["merged_into_id"],["id"],ondelete="RESTRICT")
    op.create_table("marketplace_import_batches",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("import_type",sa.String(30),nullable=False),sa.Column("source_classification",sa.String(30),nullable=False),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("column_mapping",sa.JSON(),nullable=False),*[sa.Column(x,sa.Integer(),nullable=False) for x in ("total_rows","valid_rows","invalid_rows","warning_rows","committed_rows")],sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("committed_at",sa.DateTime(timezone=True)),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"));op.create_index("ix_marketplace_import_batches_user_id","marketplace_import_batches",["user_id"])
    op.create_table("marketplace_import_rows",sa.Column("id",U,primary_key=True),sa.Column("import_batch_id",U,nullable=False),sa.Column("row_number",sa.Integer(),nullable=False),sa.Column("raw_data",sa.JSON(),nullable=False),sa.Column("normalized_data",sa.JSON()),sa.Column("validation_status",sa.String(20),nullable=False),sa.Column("warnings",sa.JSON(),nullable=False),sa.Column("errors",sa.JSON(),nullable=False),sa.Column("duplicate_status",sa.String(20)),sa.Column("proposed_product_id",U),sa.Column("action",sa.String(40)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["import_batch_id"],["marketplace_import_batches.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["proposed_product_id"],["marketplace_products.id"],ondelete="SET NULL"),sa.UniqueConstraint("import_batch_id","row_number",name="uq_marketplace_import_row_number"));op.create_index("ix_marketplace_import_rows_import_batch_id","marketplace_import_rows",["import_batch_id"])
    op.create_table("marketplace_product_aliases",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("alias",sa.String(300),nullable=False),sa.Column("normalized_alias",sa.String(300),nullable=False),sa.Column("source",sa.String(30),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["product_id"],["marketplace_products.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id","product_id","normalized_alias",name="uq_marketplace_product_alias"));
    for c in ("user_id","product_id","normalized_alias"):op.create_index(f"ix_marketplace_product_aliases_{c}","marketplace_product_aliases",[c])
    op.create_table("marketplace_product_merge_events",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("source_product_id",U,nullable=False),sa.Column("target_product_id",U,nullable=False),sa.Column("reason",sa.String(1000)),sa.Column("snapshot",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["source_product_id"],["marketplace_products.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["target_product_id"],["marketplace_products.id"],ondelete="RESTRICT"));op.create_index("ix_marketplace_product_merge_events_user_id","marketplace_product_merge_events",["user_id"])
    op.create_table("marketplace_product_split_events",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("original_product_id",U,nullable=False),sa.Column("new_product_id",U,nullable=False),sa.Column("moved_observation_ids",sa.JSON(),nullable=False),sa.Column("reason",sa.String(1000)),sa.Column("snapshot",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["original_product_id"],["marketplace_products.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["new_product_id"],["marketplace_products.id"],ondelete="RESTRICT"));op.create_index("ix_marketplace_product_split_events_user_id","marketplace_product_split_events",["user_id"])
    op.create_table("marketplace_research_presets",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("name",sa.String(100),nullable=False),sa.Column("market_location_id",U,nullable=False),sa.Column("filters",sa.JSON(),nullable=False),sa.Column("sorting",sa.JSON(),nullable=False),sa.Column("is_default",sa.Boolean(),server_default="false",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["market_location_id"],["market_locations.id"],ondelete="RESTRICT"),sa.UniqueConstraint("user_id","name",name="uq_marketplace_research_preset_name"));op.create_index("ix_marketplace_research_presets_user_id","marketplace_research_presets",["user_id"])
def downgrade():
    for t in ("marketplace_research_presets","marketplace_product_split_events","marketplace_product_merge_events","marketplace_product_aliases","marketplace_import_rows","marketplace_import_batches"):op.drop_table(t)
    op.drop_constraint("fk_marketplace_products_merged_into","marketplace_products",type_="foreignkey");op.drop_column("marketplace_products","merged_into_id");op.drop_column("marketplace_products","is_archived")
