"""Add extensible opportunity analysis and Karachi property records.

Revision ID: 20260930_0007
Revises: 20260930_0006
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20260930_0007";down_revision="20260930_0006";branch_labels=None;depends_on=None

def upgrade():
    op.create_table("opportunity_analyses",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("domain",sa.String(50),nullable=False),sa.Column("source",sa.String(200),nullable=False),sa.Column("source_reference",sa.String(1000)),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("input_snapshot",sa.JSON(),nullable=False),sa.Column("source_evidence",sa.JSON(),nullable=False),sa.Column("assumptions",sa.JSON(),nullable=False),sa.Column("calculated_metrics",sa.JSON(),nullable=False),sa.Column("recommendation",sa.JSON()),sa.Column("limitations",sa.JSON(),nullable=False),sa.Column("analyzer_version",sa.String(50),nullable=False),sa.Column("calculated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("id","user_id",name="uq_opportunity_analyses_id_user_id"))
    op.create_index("ix_opportunity_analyses_user_id","opportunity_analyses",["user_id"]);op.create_index("ix_opportunity_analyses_domain","opportunity_analyses",["domain"])
    op.create_table("property_listings",
      sa.Column("id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("city",sa.String(50),nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("source_name",sa.String(200),nullable=False),sa.Column("canonical_url",sa.String(1000)),sa.Column("source_id",sa.String(200)),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("listing_status",sa.String(40)),sa.Column("purpose",sa.String(10),nullable=False),sa.Column("property_type",sa.String(80),nullable=False),sa.Column("area_name",sa.String(200),nullable=False),sa.Column("area_amount",sa.Numeric(18,4),nullable=False),sa.Column("area_unit",sa.String(30),nullable=False),sa.Column("asking_amount",sa.Numeric(18,2),nullable=False),sa.Column("attributes",sa.JSON(),nullable=False),sa.Column("information_quality",sa.String(30),nullable=False),sa.Column("owned_by_user",sa.Boolean(),server_default="false",nullable=False),sa.Column("confirmed_valuation",sa.Numeric(18,2)),sa.Column("valuation_confirmed_at",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("city = 'Karachi'",name="ck_property_listings_karachi"),sa.CheckConstraint("purpose IN ('sale','rent')",name="ck_property_listings_purpose"),sa.CheckConstraint("area_amount > 0 AND asking_amount > 0",name="ck_property_listings_positive_values"),sa.CheckConstraint("area_unit IN ('sq_ft','sq_yd','marla_225_sq_ft','marla_272_25_sq_ft','kanal_4500_sq_ft','kanal_5445_sq_ft')",name="ck_property_listings_area_unit"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("id","user_id",name="uq_property_listings_id_user_id"))
    for name in ("user_id","observed_at","purpose","property_type","area_name"):op.create_index(f"ix_property_listings_{name}","property_listings",[name])
    op.create_index("uq_property_listings_user_url","property_listings",["user_id","canonical_url"],unique=True,postgresql_where=sa.text("canonical_url IS NOT NULL"));op.create_index("uq_property_listings_user_source_id","property_listings",["user_id","source_name","source_id"],unique=True,postgresql_where=sa.text("source_id IS NOT NULL"))
    op.create_table("property_analyses",sa.Column("analysis_id",postgresql.UUID(as_uuid=True),primary_key=True),sa.Column("user_id",postgresql.UUID(as_uuid=True),nullable=False),sa.Column("analysis_type",sa.String(20),nullable=False),sa.Column("comparable_count",sa.Integer()),sa.Column("median_asking_amount",sa.Numeric(18,2)),sa.Column("minimum_asking_amount",sa.Numeric(18,2)),sa.Column("maximum_asking_amount",sa.Numeric(18,2)),sa.Column("purchase_price",sa.Numeric(18,2)),sa.Column("monthly_rent",sa.Numeric(18,2)),sa.Column("annual_expenses",sa.Numeric(18,2)),sa.Column("annual_tax_assumption",sa.Numeric(18,2)),sa.Column("gross_yield_percent",sa.Numeric(9,4)),sa.Column("net_yield_percent",sa.Numeric(9,4)),sa.CheckConstraint("analysis_type IN ('comparables','yield')",name="ck_property_analyses_type"),sa.ForeignKeyConstraint(["analysis_id"],["opportunity_analyses.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"))
    op.create_index("ix_property_analyses_user_id","property_analyses",["user_id"])
def downgrade():
    op.drop_table("property_analyses");op.drop_index("uq_property_listings_user_source_id",table_name="property_listings");op.drop_index("uq_property_listings_user_url",table_name="property_listings");op.drop_table("property_listings");op.drop_table("opportunity_analyses")
