"""Add user-owned reviewed PSX historical evidence.

Revision ID: 20261003_0014
Revises: 20261002_0013
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20261003_0014";down_revision="20261002_0013";branch_labels=None;depends_on=None
U=postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table("psx_import_batches",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("idempotency_key",sa.String(120),nullable=False),sa.Column("original_filename",sa.String(255),nullable=False),sa.Column("source_name",sa.String(200),nullable=False),sa.Column("status",sa.String(20),nullable=False),sa.Column("total_rows",sa.Integer,nullable=False),sa.Column("valid_rows",sa.Integer,nullable=False),sa.Column("invalid_rows",sa.Integer,nullable=False),sa.Column("warning_rows",sa.Integer,nullable=False),sa.Column("committed_rows",sa.Integer,nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.Column("committed_at",sa.DateTime(timezone=True)),sa.UniqueConstraint("user_id","idempotency_key",name="uq_psx_import_idempotency"))
    op.create_index("ix_psx_import_batches_user_id","psx_import_batches",["user_id"])
    op.create_table("psx_import_rows",sa.Column("id",U,primary_key=True),sa.Column("import_batch_id",U,sa.ForeignKey("psx_import_batches.id",ondelete="CASCADE"),nullable=False),sa.Column("row_number",sa.Integer,nullable=False),sa.Column("raw_data",postgresql.JSONB,nullable=False),sa.Column("normalized_data",postgresql.JSONB),sa.Column("validation_status",sa.String(20),nullable=False),sa.Column("warnings",postgresql.JSONB,nullable=False),sa.Column("errors",postgresql.JSONB,nullable=False),sa.Column("duplicate_status",sa.String(20),nullable=False),sa.Column("action",sa.String(20),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.UniqueConstraint("import_batch_id","row_number",name="uq_psx_import_row_number"))
    op.create_index("ix_psx_import_rows_import_batch_id","psx_import_rows",["import_batch_id"])
    op.create_table("psx_price_observations",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("import_batch_id",U,sa.ForeignKey("psx_import_batches.id",ondelete="RESTRICT"),nullable=False),sa.Column("symbol",sa.String(20),nullable=False),sa.Column("observation_date",sa.Date,nullable=False),sa.Column("open_price",sa.Numeric(18,4),nullable=False),sa.Column("high_price",sa.Numeric(18,4),nullable=False),sa.Column("low_price",sa.Numeric(18,4),nullable=False),sa.Column("close_price",sa.Numeric(18,4),nullable=False),sa.Column("volume",sa.BigInteger,nullable=False),sa.Column("currency",sa.String(3),nullable=False),sa.Column("source_name",sa.String(200),nullable=False),sa.Column("adjustment_type",sa.String(10),nullable=False),sa.Column("verification_status",sa.String(20),server_default="unverified",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now(),nullable=False),sa.CheckConstraint("open_price>0 AND high_price>0 AND low_price>0 AND close_price>0",name="ck_psx_positive_prices"),sa.CheckConstraint("volume>=0",name="ck_psx_nonnegative_volume"),sa.UniqueConstraint("user_id","symbol","observation_date","adjustment_type",name="uq_psx_user_symbol_date_adjustment"))
    op.create_index("ix_psx_price_observations_user_id","psx_price_observations",["user_id"]);op.create_index("ix_psx_price_observations_import_batch_id","psx_price_observations",["import_batch_id"]);op.create_index("ix_psx_price_observations_symbol","psx_price_observations",["symbol"]);op.create_index("ix_psx_price_observations_observation_date","psx_price_observations",["observation_date"])
def downgrade():
    op.drop_table("psx_price_observations");op.drop_table("psx_import_rows");op.drop_table("psx_import_batches")
