"""Add Karachi marketplace intelligence.

Revision ID: 20261001_0009
Revises: 20260930_0008
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision="20261001_0009";down_revision="20260930_0008";branch_labels=None;depends_on=None
U=postgresql.UUID(as_uuid=True)
def upgrade():
    op.create_table("market_locations",sa.Column("id",U,primary_key=True),sa.Column("country_code",sa.String(2),nullable=False),sa.Column("country_name",sa.String(100),nullable=False),sa.Column("region_name",sa.String(100),nullable=False),sa.Column("city_name",sa.String(100),nullable=False),sa.Column("currency_code",sa.String(3),nullable=False),sa.Column("timezone",sa.String(60),nullable=False),sa.Column("is_active",sa.Boolean(),server_default="true",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False))
    op.execute("INSERT INTO market_locations (id,country_code,country_name,region_name,city_name,currency_code,timezone,is_active) VALUES ('a7b8a341-59a2-4d8d-9f05-31ea998ef001'::uuid,'PK','Pakistan','Sindh','Karachi','PKR','Asia/Karachi',true)")
    op.create_table("marketplace_products",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("normalized_name",sa.String(300),nullable=False),sa.Column("match_key",sa.String(500),nullable=False),sa.Column("brand",sa.String(100)),sa.Column("model",sa.String(100)),sa.Column("category",sa.String(100)),sa.Column("canonical_attributes",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("id","user_id",name="uq_marketplace_products_id_user_id"))
    for c in ("user_id","normalized_name","match_key","category"):op.create_index(f"ix_marketplace_products_{c}","marketplace_products",[c])
    op.create_table("marketplace_product_observations",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("marketplace",sa.String(30),nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("source_reference",sa.String(500),nullable=False),sa.Column("source_url",sa.String(1000)),sa.Column("observed_name",sa.String(300),nullable=False),sa.Column("observed_price",sa.Numeric(18,4),nullable=False),sa.Column("currency_code",sa.String(3),nullable=False),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("seller_name",sa.String(200)),sa.Column("seller_location",sa.String(200)),sa.Column("rating",sa.Numeric(3,2)),sa.Column("rating_count",sa.Integer()),sa.Column("review_count",sa.Integer()),sa.Column("sold_count",sa.Integer()),sa.Column("listing_age_days",sa.Integer()),sa.Column("raw_attributes",sa.JSON(),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["product_id","user_id"],["marketplace_products.id","marketplace_products.user_id"],ondelete="CASCADE",name="fk_marketplace_observations_owner"))
    for c in ("user_id","product_id","marketplace","observed_at"):op.create_index(f"ix_marketplace_product_observations_{c}","marketplace_product_observations",[c])
    op.create_table("marketplace_sourcing_options",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("market_location_id",U,nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("supplier_name",sa.String(200)),sa.Column("source_channel",sa.String(40),nullable=False),sa.Column("source_reference",sa.String(500)),sa.Column("unit_cost",sa.Numeric(18,2),nullable=False),sa.Column("currency_code",sa.String(3),nullable=False),sa.Column("minimum_order_quantity",sa.Numeric(18,4)),sa.Column("local_transport_cost",sa.Numeric(18,2)),sa.Column("packaging_cost",sa.Numeric(18,2)),sa.Column("lead_time_days",sa.Integer()),sa.Column("stock_available",sa.Boolean()),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["market_location_id"],["market_locations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["product_id","user_id"],["marketplace_products.id","marketplace_products.user_id"],ondelete="CASCADE",name="fk_marketplace_sourcing_owner"))
    for c in ("user_id","product_id"):op.create_index(f"ix_marketplace_sourcing_options_{c}","marketplace_sourcing_options",[c])
    op.create_table("marketplace_competition_signals",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("market_location_id",U,nullable=False),sa.Column("source_type",sa.String(30),nullable=False),sa.Column("source_reference",sa.String(500),nullable=False),sa.Column("comparable_listing_count",sa.Integer()),sa.Column("seller_count",sa.Integer()),sa.Column("lowest_price",sa.Numeric(18,2)),sa.Column("median_price",sa.Numeric(18,2)),sa.Column("highest_price",sa.Numeric(18,2)),sa.Column("price_dispersion",sa.Numeric(9,4)),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("evidence",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["market_location_id"],["market_locations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["product_id","user_id"],["marketplace_products.id","marketplace_products.user_id"],ondelete="CASCADE",name="fk_marketplace_competition_owner"))
    for c in ("user_id","product_id"):op.create_index(f"ix_marketplace_competition_signals_{c}","marketplace_competition_signals",[c])
    op.create_table("marketplace_product_rankings",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("market_location_id",U,nullable=False),sa.Column("marketplace_analysis_id",U),*[sa.Column(x,sa.Numeric(5,2)) for x in ("demand_score","margin_score","competition_score","sourcing_score","logistics_score")],sa.Column("evidence_confidence_score",sa.Numeric(5,2),nullable=False),sa.Column("overall_research_score",sa.Numeric(5,2)),sa.Column("ranking_version",sa.String(50),nullable=False),sa.Column("explanation",sa.JSON(),nullable=False),sa.Column("calculated_at",sa.DateTime(timezone=True),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["product_id"],["marketplace_products.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["market_location_id"],["market_locations.id"],ondelete="RESTRICT"),sa.ForeignKeyConstraint(["marketplace_analysis_id"],["marketplace_analyses.analysis_id"],ondelete="RESTRICT"))
    for c in ("user_id","product_id"):op.create_index(f"ix_marketplace_product_rankings_{c}","marketplace_product_rankings",[c])
    op.create_table("marketplace_product_watchlists",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("product_id",U,nullable=False),sa.Column("market_location_id",U,nullable=False),sa.Column("notes",sa.String(1000)),sa.Column("is_active",sa.Boolean(),server_default="true",nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["product_id"],["marketplace_products.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["market_location_id"],["market_locations.id"],ondelete="RESTRICT"),sa.UniqueConstraint("user_id","product_id","market_location_id",name="uq_marketplace_watchlist_entry"))
    op.create_index("ix_marketplace_product_watchlists_user_id","marketplace_product_watchlists",["user_id"])
def downgrade():
    for t in ("marketplace_product_watchlists","marketplace_product_rankings","marketplace_competition_signals","marketplace_sourcing_options","marketplace_product_observations","marketplace_products","market_locations"):op.drop_table(t)
