"""Add device-scoped reliable notification outbox.

Revision ID: 20261002_0012
Revises: 20261001_0011
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision="20261002_0012";down_revision="20261001_0011";branch_labels=None;depends_on=None
U=postgresql.UUID(as_uuid=True);events="event_type IN ('reminder_due','assistant_response_ready','feedback_review_status_changed')"

def upgrade():
    op.create_table("notification_devices",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("installation_id",U,nullable=False),sa.Column("platform",sa.String(10),nullable=False),sa.Column("display_name",sa.String(80),nullable=False),sa.Column("expo_push_token",sa.String(300),nullable=True),sa.Column("push_status",sa.String(20),server_default="unregistered",nullable=False),sa.Column("notifications_enabled",sa.Boolean(),server_default="false",nullable=False),sa.Column("session_version",sa.Integer(),server_default="1",nullable=False),sa.Column("last_seen_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("revoked_at",sa.DateTime(timezone=True),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("platform IN ('android','ios')",name="ck_notification_device_platform"),sa.CheckConstraint("push_status IN ('unregistered','active','disabled','invalid','revoked')",name="ck_notification_device_status"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id","installation_id",name="uq_notification_device_installation"),sa.UniqueConstraint("expo_push_token",name="uq_notification_device_push_token"),sa.UniqueConstraint("id","user_id",name="uq_notification_device_owner"))
    op.create_index("ix_notification_devices_user_id","notification_devices",["user_id"])
    op.create_table("notification_preferences",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("event_type",sa.String(50),nullable=False),sa.Column("enabled",sa.Boolean(),server_default="false",nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint(events,name="ck_notification_preference_event"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id","event_type",name="uq_notification_user_preference"));op.create_index("ix_notification_preferences_user_id","notification_preferences",["user_id"])
    op.create_table("device_notification_preferences",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("device_id",U,nullable=False),sa.Column("event_type",sa.String(50),nullable=False),sa.Column("enabled",sa.Boolean(),server_default="false",nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint(events,name="ck_device_notification_preference_event"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["device_id","user_id"],["notification_devices.id","notification_devices.user_id"],ondelete="CASCADE",name="fk_device_notification_preference_owner"),sa.UniqueConstraint("device_id","event_type",name="uq_device_notification_preference"));op.create_index("ix_device_notification_preferences_user_id","device_notification_preferences",["user_id"]);op.create_index("ix_device_notification_preferences_device_id","device_notification_preferences",["device_id"])
    op.create_table("notification_events",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("event_type",sa.String(50),nullable=False),sa.Column("dedupe_key",sa.String(120),nullable=False),sa.Column("deep_link",sa.String(200),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint(events,name="ck_notification_event_type"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.UniqueConstraint("user_id","event_type","dedupe_key",name="uq_notification_event_dedupe"),sa.UniqueConstraint("id","user_id",name="uq_notification_event_owner"));op.create_index("ix_notification_events_user_id","notification_events",["user_id"])
    op.create_table("notification_deliveries",sa.Column("id",U,primary_key=True),sa.Column("user_id",U,nullable=False),sa.Column("event_id",U,nullable=False),sa.Column("device_id",U,nullable=False),sa.Column("status",sa.String(30),server_default="pending",nullable=False),sa.Column("attempt_count",sa.Integer(),server_default="0",nullable=False),sa.Column("next_attempt_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("expo_ticket_id",sa.String(100),nullable=True),sa.Column("last_error_code",sa.String(60),nullable=True),sa.Column("accepted_at",sa.DateTime(timezone=True),nullable=True),sa.Column("receipt_checked_at",sa.DateTime(timezone=True),nullable=True),sa.Column("acknowledged_at",sa.DateTime(timezone=True),nullable=True),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.text("now()"),nullable=False),sa.CheckConstraint("status IN ('pending','retry','accepted','delivered','permanent_failure','dead_letter','unknown')",name="ck_notification_delivery_status"),sa.ForeignKeyConstraint(["user_id"],["users.id"],ondelete="CASCADE"),sa.ForeignKeyConstraint(["event_id","user_id"],["notification_events.id","notification_events.user_id"],ondelete="CASCADE",name="fk_notification_delivery_event_owner"),sa.ForeignKeyConstraint(["device_id","user_id"],["notification_devices.id","notification_devices.user_id"],ondelete="CASCADE",name="fk_notification_delivery_device_owner"),sa.UniqueConstraint("event_id","device_id",name="uq_notification_delivery_fanout"))
    for col in ("user_id","event_id","device_id","status","next_attempt_at","expo_ticket_id"):op.create_index(f"ix_notification_deliveries_{col}","notification_deliveries",[col])

def downgrade():
    op.drop_table("notification_deliveries");op.drop_table("notification_events");op.drop_table("device_notification_preferences");op.drop_table("notification_preferences");op.drop_table("notification_devices")
